#!/usr/bin/env sh

limelight -m config width            4
limelight -m config radius           0
limelight -m config placment         interior
limelight -m config active_color     0xffff0000
limelight -m config normal_color     0xff555555

echo "limelight configuration loaded.."
