#!/usr/bin/env sh

# general space settings
limelight -m config width              4
limelight -m config active_color       0xffff0000
limelight -m config inactive_color     0xff555555

echo "limelight configuration loaded.."
